CREATE TABLE MEMBER(
	USER_ID  VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	USER_TEL VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	NICKNAME VARCHAR2(30) NOT NULL,
	 CONSTRAINT PK_MEMBER PRIMARY KEY (USER_ID)
)
--ddfdfd
INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('1234','1234','수원','123456789','동행이름','동행닉');

INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('ID1','password1','주소1','user_TEL1','NAME1','NICKNAME1');
INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('ID','password','주소1','user_TEL1','NAME1','NICKNAME1');


CREATE TABLE EDU_APPLY_BOARD(
	BOARD_NO NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(100),
	BOARD_CONTENT CLOB,
	CATEGORY VARCHAR2(30),
	APPLY_STATUS VARCHAR2(30),
	USER_ID VARCHAR2(30),
	CONSTRAINT PK_EDU_APPLY_BOARD PRIMARY KEY (BOARD_NO),
	CONSTRAINT FK_MEMBER_EDU_APPLY_BOARD FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
)

ALTER TABLE EDU_APPLY_BOARD modify APPLY_STATUS DEFAULT '모집중'
INSERT INTO EDU_APPLY_BOARD(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,CATEGORY,USER_ID)
VALUES(EDU_APPLY_BOARD_SEQ.NEXTVAL,'BOARD_TITLE','BOARD_CONTENT','CATEGORY','ID');

CREATE TABLE EDU_APPLY_BOARD(
EDU_BOARD_NO NUMBER,
--교육 제목
EDU_BOARD_TITLE VARCHAR2(100),
--교육기간
--시작
EDU_BOARD_START_PERIOD DATE,
--마감
EDU_BOARD_END_PERIOD DATE, 
--모집기간
--시작
EDU_BOARD_APPLY_START_PERIOD DATE,
--마감
EDU_BOARD_APPLY_END_PERIOD DATE,
--모집인원 
EDU_BOARD_MEMBER_COUNT NUMBER,
--교육주소
EDU_BOARD_ADDRESS VARCHAR2(100),
--교육분야
EDU_BOARD_CATEGORY
--게시판내용
EDU_BOARD_CONTENT CLOB,
CONSTRAINT PK_EDU_APPLY_BOARD PRIMARY KEY (EDU_BOARD_NO)
--사용자 아이디
--,USER_ID  VARCHAR2(30)
--,CONSTRAINT FK_EDU_APPLY_BOARD_MEMBER FOREIGN KEY (USER_ID)
--REFERENCES EDU_APPLY_BOARD(BOARD_NO) ON DELETE CASCADE
)
ALTER TABLE EDU_APPLY_BOARD modify BOARD_NO DEFAULT EDU_APPLY_BOARD_SEQ.NEXTVAL
INSERT INTO EDU_APPLY_BOARD(
EDU_BOARD_NO,
EDU_BOARD_TITLE,
EDU_BOARD_START_PERIOD,
EDU_BOARD_END_PERIOD, 
EDU_BOARD_APPLY_START_PERIOD,
EDU_BOARD_APPLY_END_PERIOD,
EDU_BOARD_ADDRESS,
EDU_BOARD_CONTENT
--,USER_ID
)
 VALUES(
 EDU_APPLY_BOARD_SEQ.NEXTVAL,
'EDU_BOARD_TITLE',
'2023-01-01',
'2023-02-01',
'2023-01-01',
'2023-02-01',
'서울서울',
'EDU_BOARD_CONTENT'
--'user_id'
);
UPDATE EDU_APPLY_BOARD 
SET
EDU_BOARD_TITLE ='수정제목111',
EDU_BOARD_START_PERIOD='2023-02-01',
EDU_BOARD_END_PERIOD='2023-03-01', 
EDU_BOARD_APPLY_START_PERIOD='2023-02-01',
EDU_BOARD_APPLY_END_PERIOD='2023-03-01',
EDU_BOARD_MEMBER_COUNT='999',
EDU_BOARD_ADDRESS='서울서울',
EDU_BOARD_CATEGORY='수정카테고리',
EDU_BOARD_CONTENT='수정내용'
WHERE EDU_BOARD_NO='1'

CREATE TABLE LIKEBOARD(
	LIKE_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	EDU_BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_LIKE_NO PRIMARY KEY (LIKE_NO),
	CONSTRAINT FK_MEMBER_LIKEBOARD FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_LIKEBOARD FOREIGN KEY (EDU_BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(EDU_BOARD_NO) ON DELETE CASCADE	
)

INSERT INTO LIKEBOARD(LIKE_NO,USER_ID,BOARD_NO)
VALUES(LIKEBOARD_SEQ.NEXTVAL,'ID',2);

CREATE TABLE COMMENTBOARD(
	COMMENT_NO NUMBER NOT NULL,
	CONTENTCOMMENT VARCHAR2(100),
	USER_ID VARCHAR2(30) NOT NULL,
	EDU_BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_COMMENT_NO PRIMARY KEY (COMMENT_NO),
	CONSTRAINT FK_MEMBER_REPLY FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_REPLY FOREIGN KEY (EDU_BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(EDU_BOARD_NO) ON DELETE CASCADE
)

INSERT INTO COMMENTBOARD(COMMENT_NO,CONTENTCOMMENT,USER_ID,BOARD_NO)
VALUES(COMMENTBOARD_SEQ.NEXTVAL,'CONTENTCOMMENT','ID',2);

CREATE TABLE APPLY(
	APPLY_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	EDU_BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_APPLY_NO PRIMARY KEY (APPLY_NO),
	CONSTRAINT FK_MEMBER_APPLY FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_APPLY FOREIGN KEY (EDU_BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(EDU_BOARD_NO) ON DELETE CASCADE
)

INSERT INTO APPLY(APPLY_NO,USER_ID,BOARD_NO)
VALUES(APPLY_SEQ.NEXTVAL,'ID',2);

CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE EDU_APPLY_BOARD_SEQ;
CREATE SEQUENCE LIKEBOARD_SEQ;
CREATE SEQUENCE COMMENTBOARD_SEQ;
CREATE SEQUENCE APPLY_SEQ;

drop SEQUENCE EDU_APPLY_BOARD_SEQ;

COMMIT

DROP TABLE MEMBER;
DROP TABLE EDU_APPLY_BOARD;
DROP TABLE LIKEBOARD;
DROP TABLE COMMENTBOARD;
DROP TABLE APPLY;

SELECT * FROM MEMBER;
SELECT * FROM EDU_APPLY_BOARD
where EDU_BOARD_NO=100;
SELECT * FROM LIKEBOARD;
SELECT * FROM COMMENTBOARD;
SELECT * FROM APPLY;

DELETE FROM EDU_APPLY_BOARD 
WHERE EDU_BOARD_NO= 1;
DROP EDU_APPLY_BOARD CASCADE CONSTRAINT;

SELECT
rnum,
EDU_BOARD_NO,
EDU_BOARD_TITLE,
EDU_BOARD_START_PERIOD,
EDU_BOARD_APPLY_MEMBER_COUNT,
EDU_APPLY_BOARD_CATEGORY,
EDU_APPLY_BOARD_CONTENT
FROM
(SELECT row_number() over(ORDER BY EDU_BOARD_NO DESC) as
rnum,EDU_BOARD_NO,
EDU_BOARD_TITLE,
EDU_BOARD_START_PERIOD,
EDU_BOARD_APPLY_MEMBER_COUNT,
EDU_APPLY_BOARD_CATEGORY,
EDU_APPLY_BOARD_CONTENT
FROM edu_apply_board
)
WHERE rnum BETWEEN 1 and 5



SELECT 
EDU_BOARD_NO,
EDU_BOARD_TITLE,
EDU_BOARD_START_PERIOD,
EDU_BOARD_END_PERIOD, 
EDU_BOARD_APPLY_START_PERIOD,
EDU_BOARD_APPLY_END_PERIOD,
EDU_BOARD_MAX_MEMBER_COUNT,
EDU_BOARD_ADDRESS,
EDU_BOARD_CATEGORY,
EDU_BOARD_CONTENT,
EDU_BOARD_STATUS,
USER_ID
FROM EDU_APPLY_BOARD
where USER_ID='1234'

