/*
 * App URI: kosta/dynamicScript/testUpdate
 * Source Location: kosta/dynamicScript/testUpdate.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("kosta/dynamicScript/testUpdate", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * testUpdate.js
			 * Created at 2023. 8. 17. 오후 3:03:17.
			 *
			 * @author USER
			 ************************************************/

			/*
			 * "그룹 컨트롤 크기 변경" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click2(e){
				var btn1 = e.control;
				
				// 루트컨테이너
				var rootContainer = app.getContainer();
				
				// 동적으로 변경할 컨트롤 객체
				var vcGrp = app.lookup("grp1");
				
				//루트 컨테이너 안에 그룹이 존재함으로 rootContainer의 updateConstraint 해야한다. 즉 감싸고 있는 그룹을 타겟으로 잡아야한다.
				rootContainer.updateConstraint(vcGrp, {
					height: 600
				});
			}

			/*
			 * "그룹내 컨트롤 크기 변경" 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(e){
				var btn3 = e.control;
				
				// 동적으로 변경할 그룹내 컨트롤 객체
				var vcBtn = app.lookup("btn2");
				
				// 그룹컨트롤 객체
				var vcGrp = app.lookup("grp1");
				
				//그룹컨트롤 안의 컨트롤을 변경하려면 vcGrp의 updateConstraint 해야함, 즉 감싸고 있는 그룹을 타겟으로 잡아야한다.
				vcGrp.updateConstraint(vcBtn, {
					height: 200
				});
			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "그룹 컨트롤 크기 변경";
			if(typeof onBtn1Click2 == "function") {
				button_1.addEventListener("click", onBtn1Click2);
			}
			container.addChild(button_1, {
				"top": "20px",
				"left": "802px",
				"width": "179px",
				"height": "40px"
			});
			
			var group_1 = new cpr.controls.Container("grp1");
			group_1.style.css({
				"border-right-style" : "solid",
				"border-bottom-color" : "red",
				"border-top-width" : "2px",
				"border-left-style" : "solid",
				"border-right-width" : "2px",
				"border-left-color" : "red",
				"border-bottom-width" : "2px",
				"border-top-color" : "red",
				"border-right-color" : "red",
				"border-bottom-style" : "solid",
				"border-left-width" : "2px",
				"border-top-style" : "solid"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var button_2 = new cpr.controls.Button("btn2");
				button_2.value = "테스트";
				container.addChild(button_2, {
					"top": "34px",
					"left": "32px",
					"width": "162px",
					"height": "78px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "231px",
				"left": "94px",
				"width": "782px",
				"height": "164px"
			});
			
			var button_3 = new cpr.controls.Button("btn3");
			button_3.value = "그룹내 컨트롤 크기 변경";
			if(typeof onBtn3Click == "function") {
				button_3.addEventListener("click", onBtn3Click);
			}
			container.addChild(button_3, {
				"top": "104px",
				"left": "802px",
				"width": "179px",
				"height": "40px"
			});
		}
	});
	app.title = "동적으로 컨트롤 크기변경";
	cpr.core.Platform.INSTANCE.register(app);
})();
