/*
 * App URI: kosta/dynamicScript/testAddControl
 * Source Location: kosta/dynamicScript/testAddControl.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("kosta/dynamicScript/testAddControl", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * testUpdate.js
			 * Created at 2023. 8. 17. 오후 3:03:17.
			 *
			 * @author USER
			 ************************************************/

			/*
			 * "동적으로 컨트롤 추가" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){
				var btn1 = e.control;
				

				// 파일내에 존재하는 그룹컨트롤
				var vcGrp = app.lookup("grp1");
				
				// 컨트롤 동적생성
				var vcInput = new cpr.controls.InputBox();
				
				// 동적생성한 컨트롤을 그룹컨트롤에 추가
				vcGrp.addChild(vcInput, {
					autoSize: "height",  // 높이만 자동
					
				});
			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var button_1 = new cpr.controls.Button("btn1");
				button_1.value = "동적으로 컨트롤 추가";
				if(typeof onBtn1Click == "function") {
					button_1.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_1, {
					"width": "100px",
					"height": "50px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "170px",
				"left": "70px",
				"width": "851px",
				"height": "516px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "버티컬 레이아웃";
			output_1.style.css({
				"font-size" : "20px",
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"top": "83px",
				"left": "70px",
				"width": "851px",
				"height": "49px"
			});
		}
	});
	app.title = "동적으로 컨트롤 그룹에 추가(버티컬레이아웃)";
	cpr.core.Platform.INSTANCE.register(app);
})();
