
CREATE TABLE MEMBER(
	USER_ID  VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	USER_TEL VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	NICKNAME VARCHAR2(30) NOT NULL,
	CONSTRAINT PK_MEMBER PRIMARY KEY (USER_ID)
)

select * from member where user_id='java' and password='a';
INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('1234','1234','수원','123456789','동행이름','동행닉');
INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('ID1','password1','주소1','user_TEL1','NAME1','NICKNAME1');
INSERT INTO MEMBER(USER_ID,PASSWORD,ADDRESS,USER_TEL,USER_NAME,NICKNAME)
VALUES('ID','password','주소1','user_TEL1','NAME1','NICKNAME1');

CREATE TABLE EDU_APPLY_BOARD(
	BOARD_NO NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(100),
	BOARD_CONTENT CLOB,
	CATEGORY VARCHAR2(30),
	APPLY_STATUS VARCHAR2(30),
	USER_ID VARCHAR2(30),
	CONSTRAINT PK_EDU_APPLY_BOARD PRIMARY KEY (BOARD_NO),
	CONSTRAINT FK_MEMBER_EDU_APPLY_BOARD FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
)

ALTER TABLE EDU_APPLY_BOARD modify APPLY_STATUS DEFAULT '모집중'
INSERT INTO EDU_APPLY_BOARD(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,CATEGORY,USER_ID)
VALUES(EDU_APPLY_BOARD_SEQ.NEXTVAL,'BOARD_TITLE','BOARD_CONTENT','CATEGORY','ID');

CREATE TABLE LIKEBOARD(
	LIKE_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_LIKE_NO PRIMARY KEY (LIKE_NO),
	CONSTRAINT FK_MEMBER_LIKEBOARD FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_LIKEBOARD FOREIGN KEY (BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(BOARD_NO) ON DELETE CASCADE	
)

INSERT INTO LIKEBOARD(LIKE_NO,USER_ID,BOARD_NO)
VALUES(LIKEBOARD_SEQ.NEXTVAL,'ID',2);

CREATE TABLE COMMENTBOARD(
	COMMENT_NO NUMBER NOT NULL,
	CONTENTCOMMENT VARCHAR2(100),
	USER_ID VARCHAR2(30) NOT NULL,
	BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_COMMENT_NO PRIMARY KEY (COMMENT_NO),
	CONSTRAINT FK_MEMBER_REPLY FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_REPLY FOREIGN KEY (BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(BOARD_NO) ON DELETE CASCADE
)

INSERT INTO COMMENTBOARD(COMMENT_NO,CONTENTCOMMENT,USER_ID,BOARD_NO)
VALUES(COMMENTBOARD_SEQ.NEXTVAL,'CONTENTCOMMENT','ID',2);

CREATE TABLE APPLY(
	APPLY_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	BOARD_NO NUMBER NOT NULL,
	CONSTRAINT PK_APPLY_NO PRIMARY KEY (APPLY_NO),
	CONSTRAINT FK_MEMBER_APPLY FOREIGN KEY (USER_ID)
	REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_EDU_APPLY_BOARD_APPLY FOREIGN KEY (BOARD_NO)
	REFERENCES EDU_APPLY_BOARD(BOARD_NO) ON DELETE CASCADE
)

INSERT INTO APPLY(APPLY_NO,USER_ID,BOARD_NO)
VALUES(APPLY_SEQ.NEXTVAL,'ID',2);

CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE EDU_APPLY_BOARD_SEQ;
CREATE SEQUENCE LIKEBOARD_SEQ;
CREATE SEQUENCE COMMENTBOARD_SEQ;
CREATE SEQUENCE APPLY_SEQ;

COMMIT

DROP TABLE MEMBER;
DROP TABLE EDU_APPLY_BOARD;
DROP TABLE LIKEBOARD;
DROP TABLE COMMENTBOARD;
DROP TABLE APPLY;


SELECT * FROM MEMBER;
SELECT * FROM EDU_APPLY_BOARD;
SELECT * FROM LIKEBOARD;
SELECT * FROM COMMENTBOARD;
SELECT * FROM APPLY;

DELETE  FROM MEMBER WHERE PASSWORD='gjskdjflskjflk';

 

DROP EDU_APPLY_BOARD CASCADE CONSTRAINT;
