/*
 * App URI: theme/udcdialog
 * Source Location: theme/udcdialog.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("theme/udcdialog", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("yes_btn");
			button_1.value = "yes";
			button_1.style.css({
				"background-color" : "#4682a9",
				"color" : "#F6F4EB",
				"font-weight" : "bold",
				"font-size" : "1.3rem",
				"background-image" : "none"
			});
			if(typeof onYes_btnClick == "function") {
				button_1.addEventListener("click", onYes_btnClick);
			}
			container.addChild(button_1, {
				"top": "272px",
				"left": "0px",
				"width": "250px",
				"height": "80px"
			});
			
			var button_2 = new cpr.controls.Button("cancle_btn");
			button_2.value = "cancle";
			button_2.style.css({
				"background-color" : "#f6f4eb",
				"color" : "#4682a9",
				"font-weight" : "bold",
				"font-size" : "1.3rem",
				"background-image" : "none"
			});
			container.addChild(button_2, {
				"top": "272px",
				"left": "249px",
				"width": "250px",
				"height": "80px"
			});
			
			var output_1 = new cpr.controls.Output("msg");
			output_1.value = "무엇무엇을 하시겠습니까?";
			output_1.style.css({
				"font-weight" : "bold",
				"font-size" : "1.55rem",
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"top": "64px",
				"left": "93px",
				"width": "314px",
				"height": "144px"
			});
		}
	});
	app.title = "udcdialog";
	cpr.core.Platform.INSTANCE.register(app);
})();
