/*
 * App URI: deletedialog
 * Source Location: deletedialog.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("deletedialog", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * dialog.js
			 * Created at 2023. 8. 22. 오후 7:06:37.
			 *
			 * @author USER
			 ************************************************/

			/*
			 * "yes" 버튼(yes_btn)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onYes_btnClick(e){
				var yes_btn = e.control;
				var submission = app.lookup("sms1");
				var initValue = app.getHost().initValue;
				var password=initValue.param1;
				
				// 바인딩 해주기!
				console.log(initValue);
				var dMap = app.lookup("dm1");
				dMap.setValue("password", password);
				submission.send();
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSms1SubmitSuccess(e){
				var sms1 = e.control;
				var responseText = sms1.xhr.responseText;
				var any = JSON.parse(responseText);
				console.log(any.result);
				if(any.result=="success"){
					alert("회원탈퇴가 성공적으로 되었습니다.");
					window.location.href="/"
					
				}else if(any.result=="fail"){
					alert("비밀번호가 틀렸습니다.");
				}
			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			//function onSms1SubmitSuccess2(e){
			//	var sms1 = e.control;
			//	var metadata = sms1.getMetadata("registerSuccess");
			//	//map의 키를 가져온다!
			//	
			//	console.log(metadata);
			//	// metadata가 true 일때 메타데이터를 닫아준다.
			//	if(metadata == "true"){
			//		app.close(metadata);
			//	}
			//	
			//}

			/*
			 * "cancle" 버튼(no_btn)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onNo_btnClick(e){
				var no_btn = e.control;
				var dialog = app.lookup("registerdialog");
				app.close();
			};
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dm1");
			dataMap_1.parseData({
				"columns" : [{"name": "password"}]
			});
			app.register(dataMap_1);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "deleteMember";
			submission_1.addRequestData(dataMap_1);
			submission_1.addResponseData(dataMap_1, false);
			if(typeof onSms1SubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (min-width: 500px) and (max-width: 499px)", "new-screen");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("registerdialog");
			group_1.style.css({
				"background-color" : "#FFFFFF",
				"border-right-style" : "solid",
				"border-bottom-color" : "#b42e4c",
				"border-left-style" : "solid",
				"border-left-color" : "#b42e4c",
				"border-top-color" : "#b42e4c",
				"border-bottom-style" : "solid",
				"border-right-color" : "#b42e4c",
				"background-image" : "none",
				"border-top-style" : "solid"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var button_1 = new cpr.controls.Button("yes_btn");
				button_1.value = "yes";
				button_1.style.css({
					"background-color" : "#B42E4C",
					"color" : "#FFFFFF",
					"font-weight" : "bold",
					"font-size" : "1.3rem",
					"background-image" : "none"
				});
				if(typeof onYes_btnClick == "function") {
					button_1.addEventListener("click", onYes_btnClick);
				}
				container.addChild(button_1, {
					"right": "0px",
					"bottom": "0px",
					"width": "200px",
					"height": "82px"
				});
				var button_2 = new cpr.controls.Button("no_btn");
				button_2.value = "cancle";
				button_2.style.css({
					"background-color" : "#F1C4CE",
					"color" : "#AA2828",
					"font-weight" : "bold",
					"font-size" : "1.3rem",
					"background-image" : "none"
				});
				if(typeof onNo_btnClick == "function") {
					button_2.addEventListener("click", onNo_btnClick);
				}
				container.addChild(button_2, {
					"bottom": "0px",
					"left": "0px",
					"width": "193px",
					"height": "82px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "회원 정보를 탈퇴하겠습니다.";
				output_1.style.css({
					"font-weight" : "bold",
					"font-size" : "1.3rem",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "102px",
					"left": "41px",
					"width": "300px",
					"height": "98px"
				});
			})(group_1);
			if(typeof onGroupClick == "function") {
				group_1.addEventListener("click", onGroupClick);
			}
			container.addChild(group_1, {
				"top": "0px",
				"left": "0px",
				"width": "398px",
				"height": "298px"
			});
		}
	});
	app.title = "deletedialog";
	cpr.core.Platform.INSTANCE.register(app);
})();
