/*
 * App URI: findId
 * Source Location: findId.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("findId", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * findId.js
			 * Created at 2023. 8. 25. 오후 4:19:15.
			 *
			 * @author leeheeeun
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1920px)", "new-screen");
			app.supportMedia("all and (min-width: 1024px) and (max-width: 1919px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "아이디 찾기 구현 UI 만드러";
			button_1.style.css({
				"font-size" : "30px"
			});
			container.addChild(button_1, {
				"top": "291px",
				"left": "216px",
				"width": "671px",
				"height": "260px"
			});
		}
	});
	app.title = "findId";
	cpr.core.Platform.INSTANCE.register(app);
})();
