/*
 * App URI: home
 * Source Location: home.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("home", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * index.js
			 * Created at 2023. 8. 9. 오전 10:46:05.
			 *
			 * @author USER
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "labal"},
					{"name": "value"}
				],
				"rows": [
					{"labal": "HOME", "value": "home"},
					{"labal": "교육게시판", "value": "eduBoardList"},
					{"labal": "자료", "value": "myPage"},
					{"labal": "교육신청", "value": "createBoard"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("loginSession");
			dataSet_2.parseData({
				"columns" : [
					{"name": "USER_ID"},
					{"name": "PASSWORD"},
					{"name": "ADDRESS"},
					{"name": "USER_TEL"},
					{"name": "userName"},
					{"name": "NICKNAME"}
				]
			});
			app.register(dataSet_2);
			var dataMap_1 = new cpr.data.DataMap("dm1");
			dataMap_1.parseData({
				"columns" : [{"name": "userName"}]
			});
			app.register(dataMap_1);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.async = true;
			submission_1.action = "apply";
			if(typeof onSms1ReceiveJson == "function") {
				submission_1.addEventListener("receive-json", onSms1ReceiveJson);
			}
			if(typeof onSms1SubmitSuccess2 == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess2);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("sessioncheck");
			submission_2.action = "loginSessionMember";
			submission_2.addResponseData(dataSet_2, false);
			if(typeof onSms2SubmitSuccess == "function") {
				submission_2.addEventListener("submit-success", onSms2SubmitSuccess);
			}
			if(typeof onSessioncheckSubmitDone == "function") {
				submission_2.addEventListener("submit-done", onSessioncheckSubmitDone);
			}
			app.register(submission_2);
			
			var submission_3 = new cpr.protocols.Submission("logout");
			submission_3.action = "logoutMember";
			if(typeof onSms3SubmitSuccess == "function") {
				submission_3.addEventListener("submit-success", onSms3SubmitSuccess);
			}
			app.register(submission_3);
			app.supportMedia("all and (min-width: 1980px)", "new-screen");
			app.supportMedia("all and (min-width: 1024px) and (max-width: 1979px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var image_1 = new cpr.controls.Image();
			image_1.src = "theme/images/img/boyfriend_donghang.png";
			container.addChild(image_1, {
				"top": "161px",
				"left": "553px",
				"width": "223px",
				"height": "247px"
			});
			
			var image_2 = new cpr.controls.Image();
			image_2.src = "theme/images/img/woman_donghang.png";
			container.addChild(image_2, {
				"top": "161px",
				"left": "815px",
				"width": "223px",
				"height": "247px"
			});
			
			var image_3 = new cpr.controls.Image();
			image_3.src = "theme/images/img/baby_donghang.png";
			container.addChild(image_3, {
				"top": "366px",
				"left": "696px",
				"width": "205px",
				"height": "179px"
			});
			
			var image_4 = new cpr.controls.Image();
			image_4.src = "theme/images/img/talk_donghang.png";
			container.addChild(image_4, {
				"top": "200px",
				"left": "1088px",
				"width": "77px",
				"height": "88px"
			});
			
			var image_5 = new cpr.controls.Image();
			image_5.src = "theme/images/img/view_donghang.png";
			container.addChild(image_5, {
				"top": "86px",
				"left": "498px",
				"width": "78px",
				"height": "63px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "home";
	cpr.core.Platform.INSTANCE.register(app);
})();
