/*
 * App URI: selectAllowEmail
 * Source Location: selectAllowEmail.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("selectAllowEmail", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * selectAllowPassword.js
			 * Created at 2023. 8. 21. 오후 4:35:20.
			 *
			 * @author USER
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1980px)", "new-screen");
			app.supportMedia("all and (min-width: 1024px) and (max-width: 1979px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"font-weight" : "bold",
				"font-size" : "3rem"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var image_1 = new cpr.controls.Image();
				image_1.src = "theme/images/pivot/logodonghang .png";
				container.addChild(image_1, {
					"top": "91px",
					"left": "296px",
					"width": "96px",
					"height": "128px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "ITda";
				output_1.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "2rem",
					"text-align" : "left"
				});
				container.addChild(output_1, {
					"top": "143px",
					"left": "413px",
					"width": "145px",
					"height": "48px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "Accompany";
				output_2.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "1.5rem",
					"text-align" : "left"
				});
				container.addChild(output_2, {
					"top": "190px",
					"left": "410px",
					"width": "151px",
					"height": "46px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "*  이메일 본인인증하기";
				output_3.style.css({
					"font-weight" : "bold",
					"font-size" : "1.39rem"
				});
				container.addChild(output_3, {
					"top": "253px",
					"left": "154px",
					"width": "260px",
					"height": "56px"
				});
				var inputBox_1 = new cpr.controls.InputBox("userEmail");
				inputBox_1.placeholder = "ex)__________@_____";
				inputBox_1.style.css({
					"font-weight" : "normal",
					"font-size" : "1.2rem"
				});
				container.addChild(inputBox_1, {
					"top": "395px",
					"left": "154px",
					"width": "347px",
					"height": "41px"
				});
				var button_1 = new cpr.controls.Button("pwdBtn");
				button_1.value = "인증번호 받기";
				button_1.style.css({
					"background-color" : "#F6F4EB",
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "1rem",
					"background-image" : "none"
				});
				container.addChild(button_1, {
					"top": "404px",
					"left": "509px",
					"width": "126px",
					"height": "33px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "아이디가 기억나지 않는다면?";
				output_4.style.css({
					"color" : "#A7A7A7",
					"font-weight" : "normal",
					"font-size" : "1rem"
				});
				container.addChild(output_4, {
					"top": "637px",
					"left": "225px",
					"width": "217px",
					"height": "45px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "아이디 찾기";
				output_5.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "1rem"
				});
				container.addChild(output_5, {
					"top": "637px",
					"left": "448px",
					"width": "96px",
					"height": "45px"
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "ITda Accompany    |";
				output_6.style.css({
					"color" : "#91C8E4",
					"font-weight" : "normal",
					"font-size" : "1rem",
					"text-align" : "left"
				});
				container.addChild(output_6, {
					"top": "720px",
					"left": "208px",
					"width": "162px",
					"height": "21px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "고객센터 : 010-8299-1244";
				output_7.style.css({
					"color" : "#6F6F6F",
					"font-weight" : "normal",
					"font-size" : "1rem",
					"text-align" : "left"
				});
				container.addChild(output_7, {
					"top": "720px",
					"left": "371px",
					"width": "190px",
					"height": "21px"
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "01. 아이디 인증";
				output_8.style.css({
					"color" : "#333333",
					"font-weight" : "normal"
				});
				container.addChild(output_8, {
					"top": "4px",
					"left": "550px",
					"width": "108px",
					"height": "24px"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = ">";
				container.addChild(output_9, {
					"top": "4px",
					"left": "657px",
					"width": "14px",
					"height": "24px"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "02. 본인 인증";
				output_10.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold"
				});
				container.addChild(output_10, {
					"top": "4px",
					"left": "680px",
					"width": "97px",
					"height": "24px"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = ">";
				container.addChild(output_11, {
					"top": "4px",
					"left": "776px",
					"width": "14px",
					"height": "24px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "03. 비밀번호 재설정";
				container.addChild(output_12, {
					"top": "4px",
					"left": "800px",
					"width": "141px",
					"height": "24px"
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "이메일을 입력하고 인증번호 받기를 눌러주세요.";
				output_13.style.css({
					"font-weight" : "bold",
					"font-size" : "1rem"
				});
				container.addChild(output_13, {
					"top": "342px",
					"left": "154px",
					"width": "465px",
					"height": "44px"
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb1");
				inputBox_2.placeholder = "인증번호를 입력해주세요.";
				container.addChild(inputBox_2, {
					"top": "446px",
					"left": "154px",
					"width": "210px",
					"height": "40px"
				});
				var output_14 = new cpr.controls.Output();
				output_14.visible = false;
				output_14.value = "Output";
				container.addChild(output_14, {
					"top": "495px",
					"left": "153px",
					"width": "209px",
					"height": "20px"
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "다 음";
				button_2.style.css({
					"background-color" : "#91C8E4",
					"color" : "#FFFFFF",
					"font-size" : "1.23rem",
					"background-image" : "none"
				});
				container.addChild(button_2, {
					"top": "549px",
					"left": "275px",
					"width": "212px",
					"height": "40px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "20px",
				"left": "640px",
				"width": "943px",
				"height": "760px"
			});
		}
	});
	app.title = "selectAllowEmail";
	cpr.core.Platform.INSTANCE.register(app);
})();
