/*
 * App URI: selectPassword
 * Source Location: selectPassword.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("selectPassword", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * selectPassword.js
			 * Created at 2023. 8. 21. 오후 1:42:08.
			 *
			 * @author USER
			 ************************************************/

			/*
			 * 이미지에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onImageClick(e){
				var image = e.control;
				window.location.href="/"
			}

			/*
			 * "ITda Accompany    |" 아웃풋에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onOutputClick(e){
				var output = e.control;
				window.location.href="/"
			}
			/*
			 * "아이디 찾기" 아웃풋에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onOutputClick2(e){
				var output = e.control;
				window.location.href="selectIdMember.clx"
			}

			/*
			 * "비밀번호 찾으러 가기" 버튼(pwdBtn)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onPwdBtnClick(e){
				var pwdBtn = e.control;
				var id = app.lookup("userId").value;
				var dataMap = app.lookup("CheckId");
				dataMap.setValue("userId", id);
				var submission = app.lookup("sms1");
				submission.send();
				console.log(id);

			}

			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSms1SubmitSuccess2(e){
				var sms1 = e.control;
				//console.log("아이디 확인 완료");
				alert("아이디 확인 완료");
				window.location.href="selectAllowPassword.clx"
					
				}

			/*
			 * 서브미션에서 submit-error 이벤트 발생 시 호출.
			 * 통신 중 문제가 생기면 발생합니다.
			 */
			function onSms1SubmitError(e){
				var sms1 = e.control;
				var id = app.lookup("userId").value;
				if(id.length==0){
					alert("아이디를 입력해주세요");
					return false;
				}
				alert("입력하신 아이디는 존재하지 않습니다.");
			};
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("CheckId");
			dataMap_1.parseData({
				"columns" : [{"name": "userId"}]
			});
			app.register(dataMap_1);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "selectIdMember";
			submission_1.addRequestData(dataMap_1);
			submission_1.addResponseData(dataMap_1, false);
			if(typeof onSms1SubmitSuccess2 == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess2);
			}
			if(typeof onSms1SubmitError == "function") {
				submission_1.addEventListener("submit-error", onSms1SubmitError);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1980px)", "new-screen");
			app.supportMedia("all and (min-width: 1024px) and (max-width: 1979px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"font-weight" : "bold",
				"font-size" : "3rem"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var image_1 = new cpr.controls.Image();
				image_1.src = "theme/images/pivot/logodonghang .png";
				if(typeof onImageValueChange == "function") {
					image_1.addEventListener("value-change", onImageValueChange);
				}
				if(typeof onImageClick == "function") {
					image_1.addEventListener("click", onImageClick);
				}
				container.addChild(image_1, {
					"top": "91px",
					"left": "296px",
					"width": "126px",
					"height": "154px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "ITda";
				output_1.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "2rem",
					"text-align" : "left"
				});
				container.addChild(output_1, {
					"top": "158px",
					"left": "444px",
					"width": "145px",
					"height": "48px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "Accompany";
				output_2.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "1.5rem",
					"text-align" : "left"
				});
				container.addChild(output_2, {
					"top": "200px",
					"left": "444px",
					"width": "151px",
					"height": "46px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "비밀번호를 찾고자하는 아이디를 입력해주세요.";
				output_3.style.css({
					"font-weight" : "bold",
					"font-size" : "1.39rem"
				});
				container.addChild(output_3, {
					"top": "268px",
					"left": "153px",
					"width": "492px",
					"height": "56px"
				});
				var inputBox_1 = new cpr.controls.InputBox("userId");
				inputBox_1.placeholder = "   유저 아이디를 입력해주세요.\r\n";
				inputBox_1.style.css({
					"font-weight" : "normal",
					"font-size" : "1.2rem"
				});
				container.addChild(inputBox_1, {
					"top": "366px",
					"left": "139px",
					"width": "506px",
					"height": "64px"
				});
				var button_1 = new cpr.controls.Button("pwdBtn");
				button_1.value = "비밀번호 찾으러 가기";
				button_1.style.css({
					"background-color" : "#4682A9",
					"color" : "#FFFFFF",
					"font-weight" : "normal",
					"font-size" : "1.2rem",
					"background-image" : "none"
				});
				if(typeof onPwdBtnClick == "function") {
					button_1.addEventListener("click", onPwdBtnClick);
				}
				container.addChild(button_1, {
					"top": "440px",
					"left": "139px",
					"width": "506px",
					"height": "66px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "아이디가 기억나지 않는다면?";
				output_4.style.css({
					"color" : "#A7A7A7",
					"font-weight" : "normal",
					"font-size" : "1rem"
				});
				container.addChild(output_4, {
					"top": "563px",
					"left": "215px",
					"width": "234px",
					"height": "45px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "아이디 찾기";
				output_5.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold",
					"font-size" : "1rem"
				});
				if(typeof onOutputValueChange == "function") {
					output_5.addEventListener("value-change", onOutputValueChange);
				}
				if(typeof onOutputClick2 == "function") {
					output_5.addEventListener("click", onOutputClick2);
				}
				container.addChild(output_5, {
					"top": "563px",
					"left": "455px",
					"width": "96px",
					"height": "45px"
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "ITda Accompany    |";
				output_6.style.css({
					"color" : "#91C8E4",
					"font-weight" : "normal",
					"font-size" : "1rem",
					"text-align" : "left"
				});
				if(typeof onOutputClick == "function") {
					output_6.addEventListener("click", onOutputClick);
				}
				container.addChild(output_6, {
					"top": "646px",
					"left": "215px",
					"width": "162px",
					"height": "21px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "고객센터 : 010-8299-1244";
				output_7.style.css({
					"color" : "#6F6F6F",
					"font-weight" : "normal",
					"font-size" : "1rem",
					"text-align" : "left"
				});
				container.addChild(output_7, {
					"top": "646px",
					"left": "378px",
					"width": "200px",
					"height": "21px"
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "01. 아이디 인증";
				output_8.style.css({
					"color" : "#4682A9",
					"font-weight" : "bold"
				});
				container.addChild(output_8, {
					"top": "0px",
					"left": "588px",
					"width": "108px",
					"height": "24px"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = ">";
				container.addChild(output_9, {
					"top": "0px",
					"left": "695px",
					"width": "14px",
					"height": "24px"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "02. 본인 인증";
				container.addChild(output_10, {
					"top": "0px",
					"left": "718px",
					"width": "97px",
					"height": "24px"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = ">";
				container.addChild(output_11, {
					"top": "0px",
					"left": "814px",
					"width": "14px",
					"height": "24px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "03. 비밀번호 재설정";
				container.addChild(output_12, {
					"top": "0px",
					"left": "837px",
					"width": "141px",
					"height": "24px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "20px",
				"left": "625px",
				"width": "985px",
				"height": "760px"
			});
		}
	});
	app.title = "selectPassword";
	cpr.core.Platform.INSTANCE.register(app);
})();
