/*
 * App URI: kosta/emb_ex/embTab2
 * Source Location: kosta/emb_ex/embTab2.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("kosta/emb_ex/embTab2", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"}
				],
				"rows": [
					{"column1": "column11", "column2": "column21", "column3": "column31", "column4": "column41", "column5": "column51", "column6": "column61"},
					{"column1": "column12", "column2": "column22", "column3": "column32", "column4": "column42", "column5": "column52", "column6": "column62"},
					{"column1": "column13", "column2": "column23", "column3": "column33", "column4": "column43", "column5": "column53", "column6": "column63"},
					{"column1": "column14", "column2": "column24", "column3": "column34", "column4": "column44", "column5": "column54", "column6": "column64"},
					{"column1": "column15", "column2": "column25", "column3": "column35", "column4": "column45", "column5": "column55", "column6": "column65"},
					{"column1": "column16", "column2": "column26", "column3": "column36", "column4": "column46", "column5": "column56", "column6": "column66"},
					{"column1": "column17", "column2": "column27", "column3": "column37", "column4": "column47", "column5": "column57", "column6": "column67"},
					{"column1": "column18", "column2": "column28", "column3": "column38", "column4": "column48", "column5": "column58", "column6": "column68"},
					{"column1": "column19", "column2": "column29", "column3": "column39", "column4": "column49", "column5": "column59", "column6": "column69"},
					{"column1": "column110", "column2": "column210", "column3": "column310", "column4": "column410", "column5": "column510", "column6": "column610"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = true;
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["67px", "1fr"]);
			formLayout_1.setRowAutoSizing(0, true);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpHeader");
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container("grp5");
				group_2.style.setClasses(["search-box"]);
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.topMargin = "5px";
				formLayout_2.rightMargin = "5px";
				formLayout_2.bottomMargin = "5px";
				formLayout_2.leftMargin = "5px";
				formLayout_2.horizontalSpacing = "5px";
				formLayout_2.verticalSpacing = "5px";
				formLayout_2.setColumns(["1fr", "60px"]);
				formLayout_2.setRows(["25px"]);
				group_2.setLayout(formLayout_2);
				(function(container){
					var button_1 = new cpr.controls.Button("btn1");
					button_1.value = "조회";
					container.addChild(button_1, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "545px",
					"height": "37px"
				});
			})(group_1);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var group_3 = new cpr.controls.Container("grpData");
			var formLayout_3 = new cpr.controls.layouts.FormLayout();
			formLayout_3.topMargin = "0px";
			formLayout_3.rightMargin = "0px";
			formLayout_3.bottomMargin = "0px";
			formLayout_3.leftMargin = "0px";
			formLayout_3.horizontalSpacing = "0px";
			formLayout_3.verticalSpacing = "0px";
			formLayout_3.setColumns(["1fr", "550px"]);
			formLayout_3.setRows(["1fr"]);
			group_3.setLayout(formLayout_3);
			(function(container){
				var group_4 = new cpr.controls.Container("grp1");
				var formLayout_4 = new cpr.controls.layouts.FormLayout();
				formLayout_4.setColumns(["1fr"]);
				formLayout_4.setRows(["25px", "1fr"]);
				group_4.setLayout(formLayout_4);
				(function(container){
					var grid_1 = linker.grid_1 = new cpr.controls.Grid("grd1");
					grid_1.fieldLabel = "샘플 목록";
					grid_1.userAttr({"bindDataFormId": "frfCmnPgm"});
					grid_1.init({
						"dataSet": app.lookup("ds1"),
						"columnMovable": true,
						"resizableColumns": "all",
						"columns": [
							{"width": "25px"},
							{"width": "50px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"}
						],
						"header": {
							"rows": [{"height": "24px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.columnType = "checkbox";
										cell.filterable = false;
										cell.sortable = false;
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column1";
										cell.text = "column1";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 3},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column2";
										cell.text = "column2";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 4},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column3";
										cell.text = "column3";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 5},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column4";
										cell.text = "column4";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 6},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column5";
										cell.text = "column5";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 7},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.targetColumnName = "column6";
										cell.text = "column6";
									}
								}
							]
						},
						"detail": {
							"rows": [{"height": "24px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.columnType = "checkbox";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
										cell.columnType = "rowindex";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2},
									"configurator": function(cell){
										cell.columnName = "column1";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 3},
									"configurator": function(cell){
										cell.columnName = "column2";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 4},
									"configurator": function(cell){
										cell.columnName = "column3";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 5},
									"configurator": function(cell){
										cell.columnName = "column4";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 6},
									"configurator": function(cell){
										cell.columnName = "column5";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 7},
									"configurator": function(cell){
										cell.columnName = "column6";
									}
								}
							]
						}
					});
					container.addChild(grid_1, {
						"colIndex": 0,
						"rowIndex": 1
					});
				})(group_4);
				container.addChild(group_4, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_5 = new cpr.controls.Container("grp2");
				var formLayout_5 = new cpr.controls.layouts.FormLayout();
				formLayout_5.topMargin = "0px";
				formLayout_5.rightMargin = "0px";
				formLayout_5.bottomMargin = "0px";
				formLayout_5.leftMargin = "0px";
				formLayout_5.horizontalSpacing = "5px";
				formLayout_5.verticalSpacing = "5px";
				formLayout_5.setColumns(["1fr"]);
				formLayout_5.setRows(["25px", "1fr"]);
				group_5.setLayout(formLayout_5);
				(function(container){
					var group_6 = linker.group_6 = new cpr.controls.Container("grp3");
					group_6.fieldLabel = "샘플 상세";
					group_6.style.setClasses(["form-box"]);
					var formLayout_6 = new cpr.controls.layouts.FormLayout();
					formLayout_6.topMargin = "5px";
					formLayout_6.rightMargin = "5px";
					formLayout_6.bottomMargin = "5px";
					formLayout_6.leftMargin = "5px";
					formLayout_6.horizontalSpacing = "5px";
					formLayout_6.verticalSpacing = "5px";
					formLayout_6.setColumns(["120px", "1fr", "120px", "1fr"]);
					formLayout_6.setRows(["25px", "25px", "25px", "1fr"]);
					group_6.setLayout(formLayout_6);
					(function(container){
						var output_1 = new cpr.controls.Output();
						output_1.value = "Output";
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "Output";
						container.addChild(output_2, {
							"colIndex": 2,
							"rowIndex": 0
						});
						var output_3 = new cpr.controls.Output();
						output_3.value = "Output";
						container.addChild(output_3, {
							"colIndex": 0,
							"rowIndex": 1
						});
						var output_4 = new cpr.controls.Output();
						output_4.value = "Output";
						container.addChild(output_4, {
							"colIndex": 2,
							"rowIndex": 1
						});
						var inputBox_1 = new cpr.controls.InputBox("ipb1");
						inputBox_1.bind("value").toDataColumn("column1");
						container.addChild(inputBox_1, {
							"colIndex": 1,
							"rowIndex": 0
						});
						var inputBox_2 = new cpr.controls.InputBox("ipb2");
						inputBox_2.bind("value").toDataColumn("column2");
						container.addChild(inputBox_2, {
							"colIndex": 3,
							"rowIndex": 0
						});
						var inputBox_3 = new cpr.controls.InputBox("ipb3");
						inputBox_3.bind("value").toDataColumn("column3");
						container.addChild(inputBox_3, {
							"colIndex": 1,
							"rowIndex": 1
						});
						var inputBox_4 = new cpr.controls.InputBox("ipb4");
						inputBox_4.bind("value").toDataColumn("column4");
						container.addChild(inputBox_4, {
							"colIndex": 3,
							"rowIndex": 1
						});
						var inputBox_5 = new cpr.controls.InputBox("ipb7");
						inputBox_5.bind("value").toDataColumn("column5");
						container.addChild(inputBox_5, {
							"colIndex": 1,
							"rowIndex": 2
						});
						var inputBox_6 = new cpr.controls.InputBox("ipb8");
						inputBox_6.bind("value").toDataColumn("column6");
						container.addChild(inputBox_6, {
							"colIndex": 3,
							"rowIndex": 2
						});
						var output_5 = new cpr.controls.Output();
						output_5.value = "Output";
						container.addChild(output_5, {
							"colIndex": 0,
							"rowIndex": 2
						});
						var output_6 = new cpr.controls.Output();
						output_6.value = "Output";
						container.addChild(output_6, {
							"colIndex": 2,
							"rowIndex": 2
						});
					})(group_6);
					container.addChild(group_6, {
						"colIndex": 0,
						"rowIndex": 1
					});
					var group_7 = new cpr.controls.Container("grp4");
					var formLayout_7 = new cpr.controls.layouts.FormLayout();
					formLayout_7.topMargin = "0px";
					formLayout_7.rightMargin = "0px";
					formLayout_7.bottomMargin = "0px";
					formLayout_7.leftMargin = "0px";
					formLayout_7.horizontalSpacing = "5px";
					formLayout_7.verticalSpacing = "5px";
					formLayout_7.horizontalSeparatorWidth = 1;
					formLayout_7.verticalSeparatorWidth = 1;
					formLayout_7.setColumns(["1fr", "260px"]);
					formLayout_7.setRows(["25px"]);
					group_7.setLayout(formLayout_7);
					container.addChild(group_7, {
						"colIndex": 0,
						"rowIndex": 0
					});
				})(group_5);
				container.addChild(group_5, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_3);
			container.addChild(group_3, {
				"colIndex": 0,
				"rowIndex": 1
			});
			// Linking
			linker.group_6.setBindContext(new cpr.bind.GridSelectionContext(linker.grid_1));
		}
	});
	app.title = "embTab2";
	cpr.core.Platform.INSTANCE.register(app);
})();
